# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
  deploy-tag:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: publish library
          command: npm run build && npm publish
workflows:
  test:
    jobs:
      - build-and-test
  deploy:
    jobs:
      - deploy-tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/ 
          
