version: 2.1

orbs:
  node: circleci/node@4.1
jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
  deploy-tag:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: publish library
          command: npm publish
workflows:
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy-tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/ 