version: 2.1

orbs:
  node: circleci/node@4.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./
  deploy-tag:
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: publish library
          command: npm publish
workflows:
  test:
    jobs:
      - build-and-test
  deploy:
    jobs:
      - build-and-test
      - deploy-tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/ 